// Generated by Claude
import { createContext, useCallback, useContext, useMemo, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { ToastContainer, type ToastMessage, type ToastVariant } from '../components/ui/Toast';

type ToastContextValue = {
  showToast: (message: string, type?: ToastVariant) => void;
};

const ToastContext = createContext<ToastContextValue | null>(null);

const DISPLAY_MS = 3000;
const EXIT_MS = 280;

export function ToastProvider({ children }: { children: ReactNode }) {
  const [toasts, setToasts] = useState<ToastMessage[]>([]);
  const [leavingIds, setLeavingIds] = useState<Set<number>>(new Set());
  const timers = useRef<Map<number, ReturnType<typeof setTimeout>>>(new Map());

  const purge = useCallback((id: number) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
    setLeavingIds((prev) => {
      const next = new Set(prev);
      next.delete(id);
      return next;
    });
    const t = timers.current.get(id);
    if (t) {
      clearTimeout(t);
      timers.current.delete(id);
    }
  }, []);

  const startLeaving = useCallback(
    (id: number) => {
      setLeavingIds((prev) => new Set(prev).add(id));
      const t = setTimeout(() => purge(id), EXIT_MS);
      timers.current.set(id, t);
    },
    [purge],
  );

  const showToast = useCallback(
    (message: string, type: ToastVariant = 'info') => {
      const id = Date.now();
      setToasts((prev) => [...prev, { id, message, type }]);
      const timer = setTimeout(() => startLeaving(id), DISPLAY_MS);
      timers.current.set(id, timer);
    },
    [startLeaving],
  );

  const handleDismiss = useCallback(
    (id: number) => {
      if (!leavingIds.has(id)) {
        startLeaving(id);
      }
    },
    [leavingIds, startLeaving],
  );

  const value = useMemo(() => ({ showToast }), [showToast]);

  return (
    <ToastContext.Provider value={value}>
      {children}
      {createPortal(
        <ToastContainer toasts={toasts} leavingIds={leavingIds} onDismiss={handleDismiss} />,
        document.body,
      )}
    </ToastContext.Provider>
  );
}

export function useToast(): ToastContextValue {
  const ctx = useContext(ToastContext);
  if (!ctx) {
    // Fallback: no ToastProvider in tree
    return {
      showToast: (msg: string) => {
        window.alert(msg);
      },
    };
  }
  return ctx;
}
