// Generated by Claude
import { AlertCircle, XIcon } from 'lucide-react';
import { cn } from '../../lib/utils';

type ErrorAlertProps = {
  message: string;
  onDismiss?: () => void;
  className?: string;
};

export function ErrorAlert({ message, onDismiss, className }: ErrorAlertProps) {
  if (!message) return null;

  return (
    <div
      role="alert"
      className={cn(
        'flex items-start gap-3 rounded-md border border-danger/30 bg-rose-50 px-4 py-3 text-sm text-rose-800',
        className,
      )}
    >
      <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-danger" />
      <span className="flex-1">{message}</span>
      {onDismiss ? (
        <button
          type="button"
          onClick={onDismiss}
          className="shrink-0 rounded p-0.5 opacity-60 transition hover:opacity-100"
          aria-label="关闭错误提示"
        >
          <XIcon className="h-4 w-4" />
        </button>
      ) : null}
    </div>
  );
}
