// Generated by Claude
import { useEffect, useState } from 'react';
import { CheckCircle, AlertCircle, Info, XIcon } from 'lucide-react';
import { cn } from '../../lib/utils';

export type ToastVariant = 'success' | 'error' | 'info' | 'warning';

export type ToastMessage = {
  id: number;
  message: string;
  type: ToastVariant;
};

const iconMap: Record<ToastVariant, typeof CheckCircle> = {
  success: CheckCircle,
  error: AlertCircle,
  info: Info,
  warning: AlertCircle,
};

const styleMap: Record<ToastVariant, string> = {
  success: 'border-l-emerald-500 bg-emerald-50 text-emerald-900',
  error: 'border-l-red-500 bg-red-50 text-red-900',
  info: 'border-l-sky-500 bg-sky-50 text-sky-900',
  warning: 'border-l-amber-500 bg-amber-50 text-amber-900',
};

const ENTER_MS = 300;
const EXIT_MS = 250;

function ToastItem({
  item,
  leaving,
  onDismiss,
}: {
  item: ToastMessage;
  leaving: boolean;
  onDismiss: (id: number) => void;
}) {
  const [entered, setEntered] = useState(false);

  // Enter on next frame
  useEffect(() => {
    const frame = requestAnimationFrame(() => setEntered(true));
    return () => cancelAnimationFrame(frame);
  }, []);

  const Icon = iconMap[item.type] || Info;
  const isVisible = entered && !leaving;
  const duration = leaving ? EXIT_MS : ENTER_MS;

  return (
    <div
      role="status"
      className={cn(
        'pointer-events-auto rounded-lg border border-l-4 px-4 py-3 text-sm shadow-lg',
        'transition-all ease-out',
        styleMap[item.type] || styleMap.info,
      )}
      style={{
        transitionDuration: `${duration}ms`,
        opacity: isVisible ? 1 : 0,
        transform: isVisible
          ? 'translateX(0) scale(1)'
          : 'translateX(16px) scale(0.97)',
      }}
    >
      <div className="flex items-start gap-3">
        <Icon className="mt-0.5 h-4 w-4 shrink-0" />
        <span className="flex-1">{item.message}</span>
        <button
          type="button"
          onClick={() => onDismiss(item.id)}
          className="shrink-0 rounded p-0.5 opacity-60 transition-opacity hover:opacity-100"
          aria-label="关闭通知"
        >
          <XIcon className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
}

type ToastContainerProps = {
  toasts: ToastMessage[];
  leavingIds: Set<number>;
  onDismiss: (id: number) => void;
};

export function ToastContainer({ toasts, leavingIds, onDismiss }: ToastContainerProps) {
  if (toasts.length === 0) return null;

  return (
    <div
      className="pointer-events-none fixed right-4 top-4 z-50 flex w-full max-w-sm flex-col gap-2"
      aria-live="polite"
    >
      {toasts.map((t) => (
        <ToastItem
          key={t.id}
          item={t}
          leaving={leavingIds.has(t.id)}
          onDismiss={onDismiss}
        />
      ))}
    </div>
  );
}

// 保留旧导出
type LegacyToastProps = {
  message: string;
  variant?: ToastVariant;
};

const legacyVariantClass: Record<ToastVariant, string> = {
  success: 'border-success/40 bg-green-50 text-green-700',
  info: 'border-brand/40 bg-cyan-50 text-cyan-700',
  warning: 'border-warning/40 bg-amber-50 text-amber-700',
  error: 'border-danger/40 bg-rose-50 text-rose-700',
};

export function Toast({ message, variant = 'info' }: LegacyToastProps) {
  return (
    <div
      role="status"
      className={cn(
        'rounded-md border px-3 py-2 text-sm shadow-soft',
        legacyVariantClass[variant],
      )}
    >
      {message}
    </div>
  );
}
